### ISSUE TITLE
/api/Auth/Register 500 Hatası Yanlış Dto Eksik Prop

### ISSUE THREAD

**Issue by sulecelep** [Fupico/GTS-Backend#1]
/api/Auth/Register endpointine istek attığımda 500 Hatası alıyorum. Aşağıdaki hata mesajını dönüyor. Sanırım register service'inde City parametersi doldurulması zorunlu gelen bir alan, fakat dto'da City kısmı olmadığı için kaynaklanıyor olabilir.

An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'City', table 'UMS.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.

**Comment by devrimmehmet** [comment]
Teşekkürler, 
Program.cs dosyasında CORS hatası için Policy özelleştirildi ve bunun için builderden sonra bu policynin kullanımı sağlandı. 
Identity user entitysine bağlı modelde ilgili City Name Surname propertilerinin required durumları düzeltildi.
Migration dosyası düzenlendi. Şimdi tekrar deneyebilirmisin ? 
Oluşmuş veritabanını sil ve tekrar update-database yapmayı unutma lütfen.

@sulecelep #https://github.com/Fupico/GTS-Backend/commit/9e0b91be274de022583dfc7aae885a6a8ccef06d
