### ISSUE TITLE
/api/Auth/Login Email Is Not Confirmed

### ISSUE THREAD

**Issue by sulecelep** [Fupico/GTS-Backend#2]
Login olurken e-mail onayı olmadığı için 400 Hatası Alıyorum.

**Comment by devrimmehmet** [comment]
Mail adresi onaylanması zorunluydu. Mail servis yazılana kadar bu zorunluluğu ekte belirttiğim committeki gibi herkes zorunlu olmadığı haline çevirebilir ve identity konfigurasyonlarını ilgili alandan kontrol edebilir.


@sulecelep #https://github.com/Fupico/GTS-Backend/commit/1bb918808e48e7ee1c398f810f55048d157ce867
